version: '3'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana_iot
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./values.db:/var/lib/grafana/values.db
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
